### ISSUE TITLE
can't use ventura

### ISSUE THREAD

**Issue by tonylu110** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#1]
What should I do to get ventura to start

**Comment by balopez83** [comment]
I have not yet tested Ventura yet but plan to soon. Most likely will require some boot args in the config or some updates to the kexts. Since its still in beta there may not be full support yet.

**Comment by balopez83** [comment]
Ventura works now. Update your EFI to the released version 2.1.0 which adds the Boot-Arg -lilubetaall allowing you to successfully update. I have not tested using a USB installer of macOS Ventura but assume it will likely work as well. Release 2.0.0 and newer are substantial updates and so make sure you shut down fully and cold boot (no restart) after changing out the entire EFI. If you don't there will be significant issues including possible KP's
