### ISSUE TITLE
SP4 not showing "Battery" under "System Preferences" - Fix included

### ISSUE THREAD

**Issue by billabongbruno** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#10]
Hey there, once more.
Once again, great work compiling version 7.0.0 with all those fixes, which came in very helpful indeed.

Just thought I'd give you a little heads up regarding the SP4 and quite possibly some other SP devices.

This issue has been mentioned in the BigSurface Repo, under closed issue [#93](https://github.com/Xiashangning/BigSurface/issues/93) and has already had a fix proposed by [@he1833](https://github.com/he1833), right [here](https://github.com/Xiashangning/BigSurface/issues/93#issuecomment-1483956941).

The fix is posted in [@Xiashangning](https://github.com/Xiashangning)'s BigSurface main page, but I am posting here below with HEX already converted to Base64, for easier use.

Just thought you'd maybe like to include it in future versions.

Feel free to close the "issue" whenever you want.

Best regards,
Bruno.

> 
			<dict>
				<key>Base</key>
				<string></string>
				<key>BaseSkip</key>
				<integer>0</integer>
				<key>Comment</key>
				<string>SP4: Rename PM Profile</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>AAgJALIAAADw8Q==</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>AAIJALIAAADw8Q==</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>RkFDUA==</data>
			</dict>

**Comment by balopez83** [comment]
@billabongbruno thanks for drawing this to my attention. I will get this integrated into the releases. I tested and this issue impacts the surface Book as well so this patch will be an easy add as I won't need to turn it on/off for different devices. I will prob issue a new release within the next few hours.
