### ISSUE TITLE
MacOS 10.15.7 stuck on boot progress bar page

### ISSUE THREAD

**Issue by Sunburst0218** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#14]
What to do? Is there a solution?
![8DA95BEA-18F4-40F9-82A4-D725D8B4CD5D](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/99610421/ffb73ccb-3fc3-40a0-8271-2cdb3964c5c1)

**Comment by balopez83** [comment]
@Sunburst0218 i forgot to update the readme and the release information. In the process of adding support for macOS Sonoma in releases 8.x.x and higher and ensure certain features were fixed on the SP4/Book I had to select an SMBIOS that does not support Catalina anymore. If you still want to use Catalina you must use a 7.x.x or lower release. I will update the repo shortly to reflect that Catalina is no longer supported.

**Comment by Sunburst0218** [comment]
Version 7.1.0 Tested Not Supported

**Comment by balopez83** [comment]
Did you add in your SMBIOS info or leave it as is when you booted? If you added your SMBIOS info it could have caused the issue. Try adding -v to the boot-args and send screenshot of error

**Comment by balopez83** [comment]
@Sunburst0218 once you send the info above, I'll do my best to assist though I recommend using Big Sur or newer as Apple has ended security support for Catalina about 11 months ago and so the OS is no longer considered secure.

**Comment by balopez83** [comment]
I have removed Catalina from the list of supported OS's. You can try using one of the older 6.x.x or 5.x.x releases which should work with Catalina though you may lose some fixes introduced in later releases

**Comment by balopez83** [comment]
Since Catalina is now a security risk and in order to support newer versions of macOS I had to pull support for older versions of macOS, I am closing this issue as resolved. If you still have questions on this item you may re-open this ticket

**Comment by balopez83** [comment]
@Sunburst0218  Just wanted to let you know that in the process of fixing other issues I figured out why Catalina and older versions of macOS were not booting. As of release 9.0.0 you can now install and use Catalina. I have not tested older versions but they likely will boot as well. I still am not officially supporting older versions but there is not any reason that they shouldn't work unless they were not compatible with the current SMBIOS selected in release 9.0.0
