### ISSUE TITLE
SLEEPMODE ISSUE

### ISSUE THREAD

**Issue by williamoak1988** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#15]
Thanks for your great job!

Seccussfully install ventura 13.4 on my sp4 but how can i let sleep fuction work?

**Comment by balopez83** [comment]
@williamoak1988 sleep is more like hibernation on surface pro hackintoshes. Basically you need to follow the steps in quirks and fixes linked on the main readme. You have to change the sleep mode to 25 which is a Mac version of hibernation. 

By default it tries to do regular Mac sleep which is not compatible at all with the surface pro which often results is a frozen computer at a black screen or random wakes.

**Comment by balopez83** [comment]
Assuming this item is resolved now. Please re-open if you are still having issues
