### ISSUE TITLE
Sequoia

### ISSUE THREAD

**Issue by wingjson** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#24]
hi,thanks for this project,will it support macos 15 sequoia?

**Comment by balopez83** [comment]
@wingjson I have not had a chance to fully look into this but I will say it is likely that it will be supported. 

It appears Apple didn't abandon support for Kabylake which the SP4 is spoofed for so things should work however the kexts the make things work will need to also have support added.

As it stands right now though it's not supported and won't have official support until the OS is officially released later this year. 

Even if preliminary support can be added, not all kexts will get full support right away so it is likely that the OS will be a bit broken in the early months. Sonoma wasn't even fully working till a little after its official release.

**Comment by wingjson** [comment]
Thanks

**Comment by balopez83** [comment]
Sequoia is likely working at with the latest release. I have not yet tested but you are welcome to give it a go. As far as I can tell most kexts now support the latest release but since it is still considered beta do not be surprised if there are still issues.

**Comment by balopez83** [comment]
@wingjson I have updated the repo with a release that officially supports macOS Sequoia. You can now safely update to Sequoia without any risk of anything not working or breaking.

**Comment by wingjson** [comment]
Hi，I have tried to install sequoia15.1,but when loading, it will restart,and couldn't install.Then I tried to install macos14,it was ok,and i used OTA to update, after ota,it still restart.
My pro4 is i7.

**Comment by balopez83** [comment]
@wingjson what model SSD do you have in your SP4?
