### ISSUE TITLE
Can you add HoRNDIS.kext

### ISSUE THREAD

**Issue by tonylu110** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#3]
This kext can support to use phone usb hotspot
[click this link](https://mega.nz/file/WOQXHLBA#mSfN26AJnPzgZdJXIkt7JtkHSL4i7qClywFXwXlKqMs)

**Comment by balopez83** [comment]
Hi @tonylu110 yes I will add it however it will be a little bit before I am able to issue another release. I won't be able to test the kext for functionality since I don't use android but hope it does work as anticipated.

**Comment by billabongbruno** [comment]
@balopez83 , hey again.

I use Android and I can debug it for you and let you know, seeing as my phone is Android based, if you need a hand.

I have already updated to OpenCore 0.8.5, just so you know.

Unrelated topic:
I have stable Bluetooth working on my other machine.

**Comment by balopez83** [comment]
@tonylu110 as requested, I have added the HoRNDIS.kext to the latest 6.1.0 release. Let me know if this is not working for you? 

@billabongbruno can you test and let me know if it works for you as well?

**Comment by billabongbruno** [comment]
Hey there.
I will give it a try once I'm home.

Even though I'm not sure I've seen USB tethering on my Android phone.
I am currently using a Custom ROM (CrDroid 8.10 Android 12.1) on my POCO X3.
I've never used USB tethering, only hotspot and I'm not sure that's even available on my build, but I'll have a look.

**Comment by tonylu110** [comment]
@balopez83 hi
Thanks I will test it, but my keyboard doesn't work. It may be a little late

**Comment by billabongbruno** [comment]
@tonylu110 , if you are using the SP4 i3 / i5 build, you should check to see if the UTBMap.kext being loaded is the SP4 or the SB one.

I seem to recall that in the 6.1.0 build @balopez83 forgot to change that (it's only normal, it's a lot of config.plist files he's doing). Since I always sift through the config.plist to add and edit some things, I caught it and changed it.

Give it a look.

**Comment by billabongbruno** [comment]
> @balopez83 hi
> Thanks I will test it, but my keyboard doesn't work. It may be a little late

@tonylu110 

It's fixed.

Check:

https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/releases/tag/6.1.1

**Comment by billabongbruno** [comment]
@balopez83 :

HoRNDIS.kext tested and fully working.
Speeds are as high as expected from a USB connection and with a strong 4G signal in my area.
