### ISSUE TITLE
Keyboard and touch pad are unavailable

### ISSUE THREAD

**Issue by ZuoAoyu** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#7]
Hello, 
how are you? 

I came across a bug and wanted to ask you for help.

The boot menu, keyboard and touch pad can be used normally when the machine is turned on. After entering the system, although the keyboard backlight is still on, it cannot be used. I have to use an external wired keyboard.

Computer model:

Surface Pro4 i5 8+256GB

Please help me solve the problem. Thank you very much.

**Comment by billabongbruno** [comment]
> Hello, 
> how are you? 
> 
> I came across a bug and wanted to ask you for help.
> 
> The boot menu, keyboard and touch pad can be used normally when the machine is turned on. After entering the system, although the keyboard backlight is still on, it cannot be used. I have to use an external wired keyboard.
> 
> Computer model:
> 
> Surface Pro4 i5 8+256GB
> 
> Please help me solve the problem. Thank you very much.

Hey there.

Please check the config.plist to make sure it's the UTBMap-SP4.kext that's being loaded and not the UTBMap-SB.kext


I realized this in version 6.1.0 and have mentioned it in another issue.

The developer is branching the config.plist, so this is perfectly normal to occur once in a while, seeing as some things slip by sometimes.

But check that, please.

**Comment by ZuoAoyu** [comment]
> > Hello,
> > how are you?
> > I came across a bug and wanted to ask you for help.
> > The boot menu, keyboard and touch pad can be used normally when the machine is turned on. After entering the system, although the keyboard backlight is still on, it cannot be used. I have to use an external wired keyboard.
> > Computer model:
> > Surface Pro4 i5 8+256GB
> > Please help me solve the problem. Thank you very much.
> 
> Hey there.
> 
> Please check the config.plist to make sure it's the UTBMap-SP4.kext that's being loaded and not the UTBMap-SB.kext
> 
> I realized this in version 6.1.0 and have mentioned it in another issue.
> 
> The developer is branching the config.plist, so this is perfectly normal to occur once in a while, seeing as some things slip by sometimes.
> 
> But check that, please.

Thank you for your reply. I have returned to the previous version and everything has become perfect. I am very satisfied with the status quo, so I will stay in this version until Ventura is supported. 

Thank you again.

**Comment by billabongbruno** [comment]
> > > Hello,
> > > how are you?
> > > I came across a bug and wanted to ask you for help.
> > > The boot menu, keyboard and touch pad can be used normally when the machine is turned on. After entering the system, although the keyboard backlight is still on, it cannot be used. I have to use an external wired keyboard.
> > > Computer model:
> > > Surface Pro4 i5 8+256GB
> > > Please help me solve the problem. Thank you very much.
> > 
> > Hey there.
> > 
> > Please check the config.plist to make sure it's the UTBMap-SP4.kext that's being loaded and not the UTBMap-SB.kext
> > 
> > I realized this in version 6.1.0 and have mentioned it in another issue.
> > 
> > The developer is branching the config.plist, so this is perfectly normal to occur once in a while, seeing as some things slip by sometimes.
> > 
> > But check that, please.
> 
> Thank you for your reply. I have returned to the previous version and everything has become perfect. I am very satisfied with the status quo, so I will stay in this version until Ventura is supported. 
> 
> Thank you again.

You didn't need to revert to version 6.0.0.

Version 6.1.0 works perfectly, it just needs you to edit the config.plist to load the SP4 USB mapping instead of the Surface Book one.

**Comment by balopez83** [comment]
Hi @ZuoAoyu I have corrected the USB mapping issue with release [6.1.1](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/releases/tag/6.1.1). Thank you @billabongbruno for the heads up on that issue in the config.plist file.

**Comment by billabongbruno** [comment]
No worries.
I didn't open an issue because it seemed unnecessary, nor did I wanted to bother you with such a small detail, since I always thoroughly examine the config.plist and I guess I assumed everyone would too, seeing as SMBIOS info has to be added. But I see now that I was wrong.

**Comment by balopez83** [comment]
No bother, I am just glad it wasn't the Surface Book with the Surface Pro USB map as that would have prevented it from booting.

**Comment by billabongbruno** [comment]
That would have been bad, yeah.

All fixed now.
