### ISSUE TITLE
Minor oversight in latest release 6.2.0

### ISSUE THREAD

**Issue by billabongbruno** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#8]
Hey, @balopez83 , I just figured I'd drop a fair warning.

Regarding the SP4 i3/i5 plist, I should note that you left all tweaks and .aml files loaded.
Even the ones regarding the Surface Book (everything is set to true).
So it's loading both configurations for SB and SP.
It probably won't work as is.

You already know I always end up sifting through your releases in order to compare them to my personal builds and I came across this.

I haven't checked any other .plist for now, but I can do so, if you'd like.

Thank you again for your work.

Also, you should really look into the Dortania build latest releases (which I have linked earlier).

I am now running OC 0.8.9 for some time now, as well as the latest kexts we can get.

By the way, BigSurface has been updated.

Best regards,
Bruno.

**Comment by balopez83** [comment]
@billabongbruno thanks for the heads up. I was rushing and pushed it out a bit fast. I am intending on keeping all the patches and SSDT's and kexts in the config to make it easier for me to push these releases out but they should have been enabled/disabled as appropriate for each machine. I will issue a fix release if after making appropriate  adjustments. 

While it is nice to use the latest build of OC I tend to just stick to the releases just in case they accidentally introduce a bug that they later fix at their official releases. 

I will make those changes and upload a new release using the latest official Big Sur release shortly.
